In [2]:
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import numpy as np

ModuleNotFoundError: No module named 'plotly'

## Import du dataset

In [3]:
spotify = pd.read_csv('/Users/antoinettedemareuil/Documents/Databird/Projet final/df_final_genre.csv')

In [4]:
spotify

,rank,artist_names,artist_individual,track_name,release_date,album_cover,peak_rank,previous_rank,weeks_on_chart,streams,...,country,region,language,pivot,month,year,year_month,continent,artist_genrefin,music_genre
0,1,Paulo Londra,Paulo Londra,Plan A,2022-03-23,https://i.scdn.co/image/ab67616d0000b2737e1179...,1,1,4,3003411,...,Argentina,South America,Spanish,0,4,2022,2022-4,South America,argentine hip hop,latin hip hop
1,2,WOS,WOS,ARRANCARMELO,2022-04-06,https://i.scdn.co/image/ab67616d0000b273d8c994...,2,129,2,2512175,...,Argentina,South America,Spanish,0,4,2022,2022-4,South America,argentine indie,indie pop
2,3,Paulo Londra,Paulo Londra,Chance,2022-04-06,https://i.scdn.co/image/ab67616d0000b273274a28...,3,59,2,2408983,...,Argentina,South America,Spanish,0,4,2022,2022-4,South America,argentine hip hop,latin hip hop
3,5,Cris Mj,Cris Mj,Una Noche en Medellín,2022-01-21,https://i.scdn.co/image/ab67616d0000b273697ed1...,5,5,8,2080139,...,Argentina,South America,Spanish,0,4,2022,2022-4,South America,urbano chileno,other
4,6,Emilia,Emilia,cuatro veinte,2022-03-24,https://i.scdn.co/image/ab67616d0000b273116b57...,6,9,3,1923270,...,Argentina,South America,Spanish,0,4,2022,2022-4,South America,pop argentino,latin pop
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1109353,190,"Charlie Puth, Selena Gomez",Charlie Puth,We Don't Talk Anymore (feat. Selena Gomez),2015-11-05,https://i.scdn.co/image/ab67616d0000b273c0e281...,71,181,168,38376,...,Vietnam,Asia,Vietnamese,0,5,2022,2022-5,Asia,viral pop,pop
1109354,195,"Binz, Đen",Binz,Cho Mình Em,2021-04-01,https://i.scdn.co/image/ab67616d0000b273a1ca72...,32,193,56,37880,...,Vietnam,Asia,Vietnamese,0,5,2022,2022-5,Asia,v-pop,asia pop
1109355,196,"Kai Đinh, SIVAN",Kai Đinh,Thế Hệ Tan Vỡ (feat. SIVAN),2021-11-17,https://i.scdn.co/image/ab67616d0000b2734493b8...,120,200,13,37825,...,Vietnam,Asia,Vietnamese,0,5,2022,2022-5,Asia,v-pop,asia pop
1109356,197,"Maroon 5, Wiz Khalifa",Maroon 5,Payphone,2012-01-01,https://i.scdn.co/image/ab67616d0000b273fc8633...,197,-1,1,37591,...,Vietnam,Asia,Vietnamese,0,5,2022,2022-5,Asia,pop,pop
1109357,199,"Elton John, Dua Lipa, PNAU",Elton John,Cold Heart - PNAU Remix,2021-10-22,https://i.scdn.co/image/ab67616d0000b273eb842a...,114,183,30,36817,...,Vietnam,Asia,Vietnamese,0,5,2022,2022-5,Asia,piano rock,rock

# Exploration du dataset (EDA)

In [5]:
spotify.dtypes

rank                   int64
artist_names          object
artist_individual     object
track_name            object
release_date          object
album_cover           object
peak_rank              int64
previous_rank          int64
weeks_on_chart         int64
streams                int64
week_x                object
danceability         float64
energy               float64
key                    int64
mode                   int64
loudness             float64
speechiness          float64
acousticness         float64
valence              float64
tempo                float64
duration               int64
country               object
region                object
language              object
pivot                  int64
month                  int64
year                   int64
year_month            object
continent             object
artist_genrefin       object
music_genre           object
dtype: object

In [7]:
spotify.head()

,rank,artist_names,artist_individual,track_name,release_date,album_cover,peak_rank,previous_rank,weeks_on_chart,streams,...,country,region,language,pivot,month,year,year_month,continent,artist_genrefin,music_genre
0,1,Paulo Londra,Paulo Londra,Plan A,2022-03-23,https://i.scdn.co/image/ab67616d0000b2737e1179...,1,1,4,3003411,...,Argentina,South America,Spanish,0,4,2022,2022-4,South America,argentine hip hop,latin hip hop
1,2,WOS,WOS,ARRANCARMELO,2022-04-06,https://i.scdn.co/image/ab67616d0000b273d8c994...,2,129,2,2512175,...,Argentina,South America,Spanish,0,4,2022,2022-4,South America,argentine indie,indie pop
2,3,Paulo Londra,Paulo Londra,Chance,2022-04-06,https://i.scdn.co/image/ab67616d0000b273274a28...,3,59,2,2408983,...,Argentina,South America,Spanish,0,4,2022,2022-4,South America,argentine hip hop,latin hip hop
3,5,Cris Mj,Cris Mj,Una Noche en Medellín,2022-01-21,https://i.scdn.co/image/ab67616d0000b273697ed1...,5,5,8,2080139,...,Argentina,South America,Spanish,0,4,2022,2022-4,South America,urbano chileno,other
4,6,Emilia,Emilia,cuatro veinte,2022-03-24,https://i.scdn.co/image/ab67616d0000b273116b57...,6,9,3,1923270,...,Argentina,South America,Spanish,0,4,2022,2022-4,South America,pop argentino,latin pop

In [8]:
spotify.describe()

,rank,peak_rank,previous_rank,weeks_on_chart,streams,danceability,energy,key,mode,loudness,speechiness,acousticness,valence,tempo,duration,pivot,month,year
count,1.109358e+06,1.109358e+06,1.109358e+06,1.109358e+06,1.109358e+06,1.109358e+06,1.109358e+06,1.109358e+06,1.109358e+06,1.109358e+06,1.109358e+06,1.109358e+06,1.109358e+06,1.109358e+06,1.109358e+06,1109358.0,1.109358e+06,1.109358e+06
mean,1.005037e+02,4.191496e+01,8.435681e+01,3.695230e+01,6.822083e+05,6.817775e-01,6.418562e-01,5.325799e+00,5.742691e-01,-6.350271e+00,1.059119e-01,2.697027e-01,5.346442e-01,1.219058e+02,2.050575e+05,0.0,5.885851e+00,2.021270e+03
std,5.773389e+01,4.659037e+01,5.949695e+01,4.528917e+01,2.377340e+06,1.381218e-01,1.638649e-01,3.629391e+00,4.944536e-01,2.461124e+00,9.691314e-02,2.528601e-01,2.263889e-01,2.981103e+01,5.015950e+04,0.0,3.168394e+00,7.601143e-01
min,1.000000e+00,1.000000e+00,-1.000000e+00,1.000000e+00,2.067000e+03,8.590000e-02,3.160000e-03,0.000000e+00,0.000000e+00,-4.141000e+01,2.230000e-02,1.770000e-06,1.000000e-05,3.126200e+01,3.013300e+04,0.0,1.000000e+00,2.016000e+03
25%,5.100000e+01,6.000000e+00,3.100000e+01,7.000000e+00,2.470400e+04,5.910000e-01,5.350000e-01,2.000000e+00,0.000000e+00,-7.671000e+00,4.100000e-02,5.470000e-02,3.640000e-01,9.698300e+01,1.726270e+05,0.0,3.000000e+00,2.021000e+03
50%,1.010000e+02,2.200000e+01,8.200000e+01,2.000000e+01,6.335150e+04,7.010000e-01,6.600000e-01,6.000000e+00,1.000000e+00,-6.008000e+00,6.290000e-02,1.860000e-01,5.370000e-01,1.199840e+02,1.997100e+05,0.0,6.000000e+00,2.021000e+03
75%,1.510000e+02,6.500000e+01,1.350000e+02,4.800000e+01,3.025888e+05,7.870000e-01,7.660000e-01,8.000000e+00,1.000000e+00,-4.598000e+00,1.330000e-01,4.180000e-01,7.100000e-01,1.410200e+02,2.295650e+05,0.0,8.000000e+00,2.022000e+03
max,2.000000e+02,2.000000e+02,2.000000e+02,2.900000e+02,8.495293e+07,9.860000e-01,1.000000e+00,1.100000e+01,1.000000e+00,1.906000e+00,9.660000e-01,9.950000e-01,9.920000e-01,2.320180e+02,1.787030e+06,0.0,1.200000e+01,2.022000e+03

In [9]:
spotify.shape

(1109358, 31)

In [10]:
spotify.columns

Index(['rank', 'artist_names', 'artist_individual', 'track_name',
       'release_date', 'album_cover', 'peak_rank', 'previous_rank',
       'weeks_on_chart', 'streams', 'week_x', 'danceability', 'energy', 'key',
       'mode', 'loudness', 'speechiness', 'acousticness', 'valence', 'tempo',
       'duration', 'country', 'region', 'language', 'pivot', 'month', 'year',
       'year_month', 'continent', 'artist_genrefin', 'music_genre'],
      dtype='object')

In [13]:
spotify.isnull()

,rank,artist_names,artist_individual,track_name,release_date,album_cover,peak_rank,previous_rank,weeks_on_chart,streams,...,region,language,pivot,month,year,year_month,continent,artist_genrefin,music_genre,week
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1109353,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1109354,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1109355,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1109356,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1109357,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

# Cleaning du dataset

In [11]:
# Pivot est la colonne qui indique le chanteur principal, ici on garde que les ligne où pivot == 0 (chanteur principal)
spotify = spotify[spotify['pivot']==0]

In [12]:
# Conversion des colonnes au bon type
columns_to_convert_float = ['valence', 'speechiness','acousticness','loudness','tempo','energy','danceability']
columns_to_convert_int = ['mode', 'rank', 'pivot','streams', 'peak_rank', 'weeks_on_chart', 'key', 'duration']
spotify[columns_to_convert_float] = spotify[columns_to_convert_float].apply(pd.to_numeric).astype(float)
spotify[columns_to_convert_int] = spotify[columns_to_convert_int].apply(pd.to_numeric).astype(int)
spotify['week'] = pd.to_datetime(spotify['week_x'], format='%Y-%m-%d')

In [14]:
# Enlever les null et les lignes où la région n'est pas indiqué

spotify = spotify.dropna()
spotify = spotify[spotify['region'] != 'region']
spotify.shape

(1080870, 32)

# TOP50

In [15]:
# j'ai enlevé les colonnes qui font que les lignes ne sont pas en doublons
top50 = spotify.drop(columns = ['rank', 'peak_rank', 'weeks_on_chart', 'week' ])

In [16]:
#sommer les streams par continents
top50 = top50.groupby(['artist_names', 'artist_individual', 'track_name', 'danceability',
       'energy', 'key', 'mode', 'loudness', 'speechiness', 'acousticness'
      , 'valence', 'tempo', 'duration',
     'continent', 'artist_genrefin']).sum()['streams'].reset_index()

In [17]:
#avoir le max de nombre de streams par region
top50 = top50.sort_values(by=['continent', 'streams'], ascending = False )

In [18]:
#mettre un rang des streams les plus écoutés par continents
top50['sub_group_rank'] = top50.groupby('continent')['streams'].rank(ascending = False)

In [20]:
# garder les top 20 streams par continents
top50 = top50[(top50['sub_group_rank'] > 0) & (top50['sub_group_rank'] < 51)]

In [37]:
top50['top_track'] = 'Top Track'

In [21]:
result3 = round((top50['streams'].sum()/spotify['streams'].sum())*100,2)

print(f'La part du top 50 est de {result3}%')

La part du top 50 est de 15.3%

# Prédiction du hit parfait

In [38]:
#merge les 2 dataset 
spot = pd.merge(spotify, top50, on = ['artist_names', 'track_name'], how = 'left')